services:
  - type: web
    name: problemsol
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 7579169408:AAFWHKaSr5ifhCFx3AmSUYFhpSLtZCdQqjY
      - key: WEBHOOK_URL
        value: https://problemsol.onrender.com/webhook
      - key: PORT
        value: 8000