services:
  - type: web
    name: conflictresolutionbot
    env: python
    buildCommand: |
      python -m venv .venv
      . .venv/bin/activate
      pip install -r requirements.txt
    startCommand: |
      . .venv/bin/activate
      python main.py
    envVars:
      - key: BOT_TOKEN
        value: 7579169408:AAFWHKaSr5ifhCFx3AmSUYFhpSLtZCdQqjY
      - key: WEBHOOK_URL
        value: https://conflictresolutionbot.onrender.com/webhook
      - key: PORT
        value: 8000 